#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# Nothing here is written to .env, and that is deliberate: none of these values
# are used locally. They are CI credentials, and a GitHub App private key
# sitting in a working tree is a worse outcome than typing a path twice. Every
# captured value goes straight to a repository secret.
#
# Safe to re-run. Each stage checks the current state first and offers to skip.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

NPM_PKG="@croutonian/with-openapi"
JSR_SCOPE="croutonian"
JSR_PKG="with-openapi"

# ── Small helpers. The library above the marker is untouched. ─────────────

ok()   { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
bad()  { printf '  %s✗%s %s\n' "$RED" "$RESET" "$1"; }
todo() { printf '  %s·%s %s\n' "$DIM" "$RESET" "$1"; }

have_secret() { gh secret list --json name --jq '.[].name' 2>/dev/null | grep -qx "$1"; }

# installed_apps — slugs of the GitHub Apps installed on the owner. Needs
# admin:org for an organization. Fails rather than printing nothing when it
# cannot tell, because "I cannot see" and "nothing is installed" must not
# collapse into the same answer.
installed_apps() {
  if [[ "${OWNER_TYPE:-User}" == "Organization" ]]; then
    gh api "/orgs/$OWNER/installations" --jq '.installations[].app_slug' 2>/dev/null
  else
    gh api "/user/installations" --jq '.installations[].app_slug' 2>/dev/null
  fi
}

# app_state SLUG — installed | absent | unknown
app_state() {
  local list
  if ! list="$(installed_apps)"; then printf 'unknown'; return; fi
  if grep -qx "$1" <<<"$list"; then printf 'installed'; else printf 'absent'; fi
}

# confirm_app_installed SLUG LABEL — the fallback when the API cannot answer.
confirm_app_installed() {
  step "App settings → 'Install App' → $OWNER → 'Only select repositories' → $REPO"
  confirm "Is $2 installed on $REPO?" || SKIPPED+=("install $2 on $REPO")
}

# npm_pkg_exists — whether the package name is on the registry yet. Decides
# whether a trusted publisher can be configured at all.
#
# The unique query parameter is not decoration. registry.npmjs.org sits behind
# Cloudflare with `cache-control: max-age=300`, so for five minutes after a
# publish this path still answers 404 from cache — exactly when a wizard is
# most likely to ask. A `Cache-Control: no-cache` request header is ignored;
# varying the URL is what actually reaches the origin.
npm_pkg_exists() {
  curl -fsS -o /dev/null \
    "https://registry.npmjs.org/$(printf '%s' "$NPM_PKG" | sed 's|/|%2F|')?cb=$RANDOM$RANDOM" \
    2>/dev/null
}

# jsr_linked_repo — the GitHub repo linked on JSR, or empty when unlinked.
jsr_linked_repo() {
  local json owner name
  json="$(curl -fsS "https://api.jsr.io/scopes/${JSR_SCOPE}/packages/${JSR_PKG}" 2>/dev/null)" || return 0
  # Narrow to the githubRepository object first, so the owner/name of the
  # *package* are not mistaken for the repository's.
  json="$(printf '%s' "$json" | sed -n 's/.*"githubRepository":{\([^}]*\)}.*/\1/p')"
  [[ -n "$json" ]] || return 0
  owner="$(printf '%s' "$json" | sed -n 's/.*"owner":"\([^"]*\)".*/\1/p')"
  name="$(printf '%s' "$json" | sed -n 's/.*"name":"\([^"]*\)".*/\1/p')"
  [[ -n "$owner" && -n "$name" ]] && printf '%s/%s' "$owner" "$name"
}

# read_path VAR "Prompt" — a file path, tolerating what a terminal drag-and-drop
# leaves behind: surrounding quotes, escaped spaces, a trailing space, and ~.
read_path() {
  local key="$1" input
  printf '  %s%s%s ' "$BOLD" "$2" "$RESET"
  read -r input || true
  input="${input%"${input##*[![:space:]]}"}"
  input="${input#"${input%%[![:space:]]*}"}"
  input="${input%\'}"; input="${input#\'}"
  input="${input%\"}"; input="${input#\"}"
  input="${input//\\ / }"
  [[ "$input" == "~"* ]] && input="${HOME}${input:1}"
  printf -v "$key" '%s' "$input"
}

banner "Release setup for $NPM_PKG"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — what is already done"

if ! command -v gh >/dev/null 2>&1; then
  bad "The GitHub CLI is not installed. See https://cli.github.com then re-run."
  exit 1
fi
if ! gh auth status >/dev/null 2>&1; then
  bad "The GitHub CLI is not authenticated. Run: gh auth login"
  exit 1
fi
ok "gh is installed and authenticated"

REPO="$(gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null || true)"
if [[ -z "$REPO" ]]; then
  bad "Could not resolve a GitHub repository from this directory."
  note "Run this from the repository root: npm run setup-releases"
  exit 1
fi
ok "repository: $REPO"

OWNER="${REPO%%/*}"
OWNER_TYPE="$(gh api "repos/$REPO" --jq .owner.type 2>/dev/null || echo User)"
if [[ "$(gh api "repos/$REPO" --jq .permissions.admin 2>/dev/null)" != "true" ]]; then
  warn "You do not have admin on $REPO — setting secrets will fail."
  confirm "Continue anyway?" || exit 1
fi

printf '\n'
say "Current state:"
have_secret GH_APP_ID && have_secret GH_APP_PRIVATE_KEY \
  && ok "release App secrets present" || todo "release App not configured (stage 2)"
case "$(app_state pkg-pr-new)" in
  installed) ok "pkg.pr.new App installed" ;;
  absent)    todo "pkg.pr.new App not installed (stage 3)" ;;
  *)         todo "pkg.pr.new App — cannot tell without the admin:org scope" ;;
esac
if npm_pkg_exists; then
  ok "$NPM_PKG exists on npm — a trusted publisher can be configured"
else
  todo "$NPM_PKG is not on npm yet — stage 4 publishes it once from here"
fi
have_secret NPM_TOKEN && note "  NPM_TOKEN is set — stage 4 offers to remove it" || true
JSR_REPO="$(jsr_linked_repo)"
[[ -n "$JSR_REPO" ]] && ok "JSR linked to $JSR_REPO" || todo "JSR package not linked to a repo (stage 5)"

printf '\n'
pause "Press Enter to begin."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "GitHub App — lets release-please open its PR"

say "release-please has to open a pull request. This org does not let GitHub"
say "Actions do that, so the release run fails after creating the branch:"
note "  \"GitHub Actions is not permitted to create or approve pull requests\""
say "A GitHub App is not GitHub Actions, so the policy does not cover it."
printf '\n'

if have_secret GH_APP_ID && have_secret GH_APP_PRIVATE_KEY; then
  ok "GH_APP_ID and GH_APP_PRIVATE_KEY are already set"
  confirm "Replace them?" && APP_STAGE=yes || APP_STAGE=no
else
  APP_STAGE=yes
fi

if [[ "$APP_STAGE" == "yes" ]]; then
  if [[ "$OWNER_TYPE" == "Organization" ]]; then
    APP_NEW="https://github.com/organizations/$OWNER/settings/apps/new"
  else
    APP_NEW="https://github.com/settings/apps/new"
  fi
  # The form is pre-filled through query parameters, so the permissions cannot
  # be got wrong by hand — Contents and Pull requests write, no webhook.
  APP_NEW="$APP_NEW?name=$OWNER-release-bot&description=Opens+release-please+pull+requests&public=false&webhook_active=false&contents=write&pull_requests=write"
  open_url "$APP_NEW"
  step "The form is pre-filled. Scroll down and click 'Create GitHub App'."
  note "  Homepage URL is required — any URL works, e.g. https://github.com/$REPO"
  printf '\n'
  ask APP_ID "Paste the App ID shown at the top of the next page:"
  printf '\n'
  step "On that same page, scroll to 'Private keys' → 'Generate a private key'."
  step "A .pem file downloads. Drag it into this terminal, or paste its path."
  read_path PEM_PATH "Path to the .pem file:"

  if [[ ! -f "$PEM_PATH" ]]; then
    bad "No file at: $PEM_PATH"
    SKIPPED+=("GH_APP_PRIVATE_KEY — .pem not found, re-run this wizard")
  elif ! grep -q "BEGIN.*PRIVATE KEY" "$PEM_PATH"; then
    bad "That file does not look like a private key: $PEM_PATH"
    SKIPPED+=("GH_APP_PRIVATE_KEY — file was not a PEM, re-run this wizard")
  else
    set_secret GH_APP_ID "$APP_ID"
    set_secret GH_APP_PRIVATE_KEY "$(cat "$PEM_PATH")"
    printf '\n'
    warn "Delete the downloaded .pem now — it is a live credential:"
    note "  rm '$PEM_PATH'"
  fi

  printf '\n'
  step "Now install it, from the page you are already on:"
  step "  left sidebar → 'Install App' → $OWNER → 'Install'"
  step "  → 'Only select repositories' → $REPO"
  note "  Creating an App does not install it; this step is easy to miss."
  pause "Press Enter once the App is installed."
fi

# Installation is independent of credentials: an App can exist, have its ID and
# key sitting in secrets, and still not be installed on the repository — which
# is the actual blocker. So this is checked on every run, not only on the run
# that enters the keys.
printf '\n'
RELEASE_APP="${OWNER}-release-bot"
case "$(app_state "$RELEASE_APP")" in
  installed)
    ok "the App '$RELEASE_APP' is installed on $OWNER"
    ;;
  absent)
    warn "No App called '$RELEASE_APP' is installed on $OWNER."
    say "Installed right now:"
    installed_apps | sed 's/^/      /' || true
    note "  If yours is listed above under a different name, that is fine."
    confirm_app_installed "$RELEASE_APP" "the release App"
    ;;
  *)
    note "Cannot list installed Apps here (needs the admin:org scope)."
    confirm_app_installed "$RELEASE_APP" "the release App"
    ;;
esac

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "pkg.pr.new — branch preview builds"

say "Every branch push publishes an installable preview of the package."
say "Without the App the preview job warns and skips; nothing else breaks."
printf '\n'

PKG_APP_STATE="$(app_state pkg-pr-new)"
if [[ "$PKG_APP_STATE" == "installed" ]]; then
  ok "pkg.pr.new is installed on $OWNER"
  note "  Per-repository selection is not readable here, so if previews still"
  note "  fail, check that $REPO is among the selected repositories."
else
  [[ "$PKG_APP_STATE" == "absent" ]] \
    && todo "pkg.pr.new is not installed on $OWNER" \
    || note "Cannot list installed Apps here (needs the admin:org scope)."
  open_url "https://github.com/apps/pkg-pr-new"
  step "Click 'Install' (or 'Configure' if it is installed elsewhere already)."
  step "Choose $OWNER, then 'Only select repositories' → $REPO."
  pause "Press Enter once that is done."
fi

printf '\n'
if confirm "Re-run the last preview build to check it end to end? (~1 min)"; then
  PREVIEW_RUN="$(gh run list --workflow=preview.yml --limit 1 --json databaseId --jq '.[0].databaseId' 2>/dev/null || true)"
  if [[ -n "$PREVIEW_RUN" ]]; then
    gh run rerun "$PREVIEW_RUN" >/dev/null 2>&1 || warn "could not re-run $PREVIEW_RUN"
    sleep 5   # the re-run is queued asynchronously; watching too early misses it
    gh run watch "$PREVIEW_RUN" --exit-status >/dev/null 2>&1 \
      && ok "preview published" \
      || warn "preview still failing — check: gh run view $PREVIEW_RUN --log-failed"
  else
    note "No previous preview run to re-run; it will run on your next push."
  fi
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "npm — publishing"

# No deep links into npmjs.com here on purpose. It serves 403 to anything that
# is not a browser, so a URL cannot be checked before shipping it — and the
# first attempt at this stage guessed a token page that did not exist. Only the
# canonical package URL is opened; everything past it is npm's own documented
# click path.

NPM_PUBLISHED=no

if ! npm_pkg_exists; then
  say "Trusted publishing attaches to a package that already exists, and"
  say "$NPM_PKG does not yet. Publishing once from here is the way in:"
  say "your login, your 2FA, no token involved. CI takes over afterwards."
  if have_secret NPM_TOKEN; then
    printf '\n'
    note "  NPM_TOKEN is set, but a token cannot answer npm's one-time password"
    note "  prompt. If the account requires 2FA for writes, a CI publish fails"
    note "  with EOTP — so this is not offered as an alternative."
  fi
  printf '\n'

  NPM_USER="$(npm whoami 2>/dev/null || true)"
  if [[ -z "$NPM_USER" ]]; then
    step "Not logged in to npm. Running 'npm login' — it opens a browser."
    note "  A stale token in ~/.npmrc reads as logged out, and makes publish"
    note "  fail with a confusing 404 rather than an auth error."
    pause "Press Enter to start the login."
    npm login || true
    NPM_USER="$(npm whoami 2>/dev/null || true)"
  fi

  if [[ -z "$NPM_USER" ]]; then
    bad "Still not logged in to npm."
    SKIPPED+=("npm login, then: npm publish --access public")
  else
    ok "logged in to npm as $NPM_USER"
    VERSION="$(node -p "require('./package.json').version" 2>/dev/null || echo '?')"
    printf '\n'
    warn "This publishes $NPM_PKG@$VERSION to the public registry."
    note "  A published version is permanent — it can be deprecated, but the"
    note "  number can never be reused. Nothing else in this wizard is like this."
    printf '\n'
    if confirm "Publish $NPM_PKG@$VERSION now?"; then
      if npm run build && npm publish --access public; then
        ok "published $NPM_PKG@$VERSION"
        NPM_PUBLISHED=yes
      else
        bad "publish failed — see the output above"
        SKIPPED+=("npm publish --access public")
      fi
    else
      SKIPPED+=("first publish: npm publish --access public (then re-run this wizard)")
    fi
  fi
  printf '\n'
fi

# Trust the publish that just happened over a re-query: the CDN would answer
# from a cache written before it. And where the registry still says no, ask —
# a wrong reading should never be able to end the stage on its own.
NPM_READY=no
if [[ "$NPM_PUBLISHED" == "yes" ]] || npm_pkg_exists; then
  NPM_READY=yes
else
  printf '\n'
  warn "The registry says $NPM_PKG is not published."
  note "  It caches for five minutes, so a very recent publish can read as"
  note "  missing. https://www.npmjs.com/package/$NPM_PKG settles it."
  confirm "Is it published?" && NPM_READY=yes
fi

if [[ "$NPM_READY" == "yes" ]]; then
  say "Now point npm at this repository, so the release workflow can publish"
  say "with its OIDC token and nothing has to store a credential."
  printf '\n'
  open_url "https://www.npmjs.com/package/$NPM_PKG"
  step "On the package page: 'Settings' tab → 'Trusted publishing'."
  step "Select publisher: GitHub Actions."
  step "Organization or user: ${REPO%%/*}"
  step "Repository: ${REPO##*/}"
  step "Workflow filename: release.yml"
  note "  Filename only, not a path. Leave 'Environment name' empty."
  pause "Press Enter once the trusted publisher is saved."

  if have_secret NPM_TOKEN; then
    printf '\n'
    say "NPM_TOKEN is only a fallback for publishing without a trusted"
    say "publisher. With one configured, the repo needs no npm credential."
    if confirm "Delete the NPM_TOKEN secret?"; then
      gh secret delete NPM_TOKEN >/dev/null 2>&1 \
        && ok "deleted NPM_TOKEN" \
        || warn "could not delete NPM_TOKEN"
    else
      SKIPPED+=("delete the NPM_TOKEN secret once trusted publishing is verified")
    fi
  fi
else
  SKIPPED+=("npm trusted publisher — set it up after the first publish (re-run this wizard)")
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "JSR — link the package to this repository"

JSR_REPO="$(jsr_linked_repo)"
if [[ "$JSR_REPO" == "$REPO" ]]; then
  ok "already linked to $JSR_REPO"
else
  [[ -n "$JSR_REPO" ]] && warn "linked to $JSR_REPO, expected $REPO"
  say "Linking lets the release workflow publish with its OIDC token, with no"
  say "JSR credential stored in the repository."
  printf '\n'
  open_url "https://jsr.io/@${JSR_SCOPE}/${JSR_PKG}/settings"
  step "Under 'GitHub Repository', enter: $REPO"
  step "Click 'Link'."
  pause "Press Enter once linked."

  JSR_REPO="$(jsr_linked_repo)"
  [[ "$JSR_REPO" == "$REPO" ]] && ok "verified: JSR is linked to $JSR_REPO" \
    || SKIPPED+=("link the JSR package to $REPO at https://jsr.io/@${JSR_SCOPE}/${JSR_PKG}/settings")
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Verify"

say "Re-reading everything from the source rather than from what we just did:"
printf '\n'

have_secret GH_APP_ID && have_secret GH_APP_PRIVATE_KEY \
  && ok "release App secrets set" \
  || bad "release App secrets missing — release-please cannot open its PR"

if npm_pkg_exists; then ok "$NPM_PKG published"
else todo "$NPM_PKG not published yet"; fi

have_secret NPM_TOKEN && warn "NPM_TOKEN still set — not needed once trusted publishing works" \
  || ok "no npm credential stored in the repository"

JSR_REPO="$(jsr_linked_repo)"
[[ "$JSR_REPO" == "$REPO" ]] && ok "JSR linked to $JSR_REPO" || bad "JSR not linked"

printf '\n'
say "Next: push to main. release-please opens a release PR; merging it"
say "publishes to npm and JSR."
note "  Watch it: gh run watch \$(gh run list --workflow=release.yml --limit 1 --json databaseId --jq '.[0].databaseId')"

finish
